import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import DownloadCard from "../components/DownloadCard";
import GlanceCard from "../components/GlanceCard";
import MissionAndVision from "../components/MissionAndVission";
import OurValues from "../components/OurValues";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Purbani Document Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-main-global h-screen">
        <Navbar />
        <DownloadCard />
        <GlanceCard />
        <MissionAndVision />
        <OurValues />
        <Footer />
      </main>

      <footer>
      </footer>
    </div>
  );
}
